language: python
os: linux
dist: xenial

env:
  global:
    PIP_PREFER_BINARY=true

python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
  - "3.10"
  - "3.11"

install:
  - pip install --upgrade pip
  - pip install -r requirements_ci.txt
  - pip install pytest
  - pip install pytest-cov
  - pip install coveralls

# command to run tests
script:
   pytest --cov=pyod/

after_success:
  - coveralls

notifications:
  email:
    recipients:
      - kq441morita@gmail.com
  on_success: never # default: change
  on_failure: always # default: always
